In [ ]:
#Numpy

In [ ]:
#Numpy
-Numerical Python
-Core library for scentific computing
-Fast numerical calculations


SyntaxError: invalid syntax (ipython-input-3914181475.py, line 2)

In [ ]:
#Python List vs Numpy array
import numpy as np
py_list=[1,2,3]
np_array=np.array([1,2,3])
print(py_list * 2)
print(np_array * 2)


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
# Creating array in numpy
arr=[1,5,0.8,0.6,0.3]
np_arr=np.array(arr)

In [ ]:
np_arr#default float

array([1. , 5. , 0.8, 0.6, 0.3])

In [ ]:
#Generating zeros
np.zeros((5,2)) #default float

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#Generating ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Generating nd array with same value
np.full((5,2,3), fill_value=6,dtype=np.float32)

array([[[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.]]], dtype=float32)

In [ ]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Using arrange
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(5,15,2) # it indicates the number from 5 to 15 with 2 space gaps.

array([ 5,  7,  9, 11, 13])

In [ ]:
#Using linspace and logspace
np.linspace(5,10,num=10) # evenly spaced(vaneko 5 to 10 samma lai 10 choti spaced garauni)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [ ]:
np.logspace(0,3,num=4, base=10) #return numbers spaced evenly on a log scale

array([   1.,   10.,  100., 1000.])

In [ ]:
#Using full
np.full((5,2), fill_value=2,dtype=np.int32)#Generate nd array with same value

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]], dtype=int32)

In [ ]:
#Array attributes:
arr1=np.array([.2,.3,4.8,.4,77,9.1])
print(arr1)
print(arr1.dtype)

[ 0.2  0.3  4.8  0.4 77.   9.1]
float64


In [ ]:
arr1=np.array([.2,.3,4.8,.4,77,9.1],dtype=np.int64)
print(arr1) # roundoff garera value linna aagdai ko matra linxa
print(arr1.dtype)

[ 0  0  4  0 77  9]
int64


In [ ]:
#Random and Reproducibility
import random
np.random.seed(1337) # reproducibility
np.random.randint(1,10)# Random integer from [1,10]

8

In [ ]:
np.random.randint(0,100,size=5)#1D array

array([61, 92, 39, 89, 39])

In [ ]:
np.random.randint(10,50,size=(2,3)) # 2D arary(identify array by brackets )

array([[36, 28, 30],
       [18, 19, 16]])

In [ ]:
#np.random.rand() - random floats(0,1) used in ml weights,probabilities
np.random.rand(5)

array([0.98354861, 0.44322487, 0.78955834, 0.79411858, 0.36126157])

In [ ]:
np.random.rand(2,3)

array([[0.41610394, 0.58425813, 0.76017177],
       [0.18780841, 0.28816715, 0.67021886]])

In [ ]:
np.random.random((2,3))#same as rand()but takes only one arg for 2D array

array([[0.49964826, 0.17856868, 0.4131413 ],
       [0.19919524, 0.5316994 , 0.8323707 ]])

In [ ]:
#np.random.randn()-random from standard normal distribution
#can be negative and mostly around 0
import numpy as np
np.random.standard_normal((2,4))


array([[ 0.07095015,  0.55870726,  0.20981128, -1.41554803],
       [-0.01064554,  0.47794236, -0.57493331, -0.78283619]])

In [ ]:
array=[1,2,3,4,5]
np.random.shuffle(array)
print(array)

[1, 4, 2, 5, 3]


In [ ]:
#Indexing Slicing
import numpy as np
a=np.arange(10)
print(a)
print(a[2])
print(a[-1])
print(a[2:8:2])
a2=a.reshape(2,5)
print(a2)
print(a2[:1,1:3])

[0 1 2 3 4 5 6 7 8 9]
2
9
[2 4 6]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2]]


In [ ]:
M=np.arange(12).reshape(3,4)
print("M\n/",M)
print("row 1:",M[1])
print("element(2,3):",M[2,3])

M
/ [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row 1: [4 5 6 7]
element(2,3): 11


In [ ]:
#1D array
#array[start:end:step]
arr=np.array([10,20,30,40,50,60])
print(arr)


[10 20 30 40 50 60]


In [ ]:
arr[1:4]

array([20, 30, 40])

In [ ]:
arr[:3]

array([10, 20, 30])

In [ ]:
arr[:]

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr[::2]

array([10, 30, 50])

In [ ]:
#2D array slicing
#array[row_slice,column_slice]
mat=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(mat)



[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
mat[0:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
mat[1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [ ]:
mat[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [ ]:
#3D array slicing
#cube[class][row][column]
cube=np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [70,80,90],
        [100,110,120]
    ]

])
print(cube)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [ ]:
cube[0,:,:]

array([[10, 20, 30],
       [40, 50, 60]])